[project]
name = "ct-clip"
version = "0.1.0"
requires-python = ">=3.10,<3.12"
dependencies = [
    "beartype",
    "einops>=0.6",
    "ftfy",
    "regex",
    "torch",
    "torchvision",
    "XlsxWriter",
    "h5py",
    "matplotlib",
    "seaborn",
    "wilds",
    "ImageNetV2_pytorch",
    "click",
    "appdirs",
    "attr",
    "nltk"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
ImageNetV2_pytorch = { git = "https://github.com/modestyachts/ImageNetV2_pytorch" }
